version: '3.9'

services:
  back:
    container_name: back-docker
    build: ./back
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database/books
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 5000"
    depends_on:
      database:
        condition: service_healthy

  front:
      container_name: front-docker
      build: ./front
      ports:
      - '3000:3000'
      command: "npm start"
      depends_on:
        - back

  database:
      container_name: database-docker
      build: ./database
      volumes:
        - /docker-entrypoint-initdb.d
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 10
      