"""Create book

Revision ID: 1019307f3a93
Revises: 5255716a3810
Create Date: 2022-11-14 03:46:58.235191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1019307f3a93'
down_revision = '5255716a3810'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
