"""Fix delete 3

Revision ID: 18a20701964b
Revises: c373a0f766f4
Create Date: 2022-11-20 20:09:37.690784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a20701964b'
down_revision = 'c373a0f766f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
