"""Fix move

Revision ID: 2254d19487dc
Revises: b7926e537d6b
Create Date: 2022-11-20 19:04:20.974229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2254d19487dc'
down_revision = 'b7926e537d6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
