"""Get authors

Revision ID: 22f2b1b119c9
Revises: de973418622b
Create Date: 2022-11-13 21:20:36.151996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f2b1b119c9'
down_revision = 'de973418622b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
