"""Fix delete 7

Revision ID: 36463245d9df
Revises: ff8b2f36d46f
Create Date: 2022-11-20 20:26:03.033796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36463245d9df'
down_revision = 'ff8b2f36d46f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
