"""Fix delete 4

Revision ID: 3877ad711dba
Revises: 18a20701964b
Create Date: 2022-11-20 20:12:49.047089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3877ad711dba'
down_revision = '18a20701964b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
