"""Get authors

Revision ID: 433cf6c9dd97
Revises: deb980edf89e
Create Date: 2022-11-13 21:57:48.761424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433cf6c9dd97'
down_revision = 'deb980edf89e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
