"""Delete vook

Revision ID: 440d11fffccd
Revises: ce05225d3660
Create Date: 2022-11-14 03:47:47.103913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440d11fffccd'
down_revision = 'ce05225d3660'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
