"""Create author

Revision ID: 5255716a3810
Revises: 95de9086e9d2
Create Date: 2022-11-14 03:46:35.501336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5255716a3810'
down_revision = '95de9086e9d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
