"""Move books

Revision ID: 70b5e4e26d04
Revises: 74adab71486c
Create Date: 2022-11-14 03:15:02.898359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b5e4e26d04'
down_revision = '74adab71486c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
