"""Move books

Revision ID: 74adab71486c
Revises: 433cf6c9dd97
Create Date: 2022-11-14 03:11:02.308599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74adab71486c'
down_revision = '433cf6c9dd97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
