"""Edit author

Revision ID: 891ed79e7711
Revises: 1019307f3a93
Create Date: 2022-11-14 03:47:16.786598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891ed79e7711'
down_revision = '1019307f3a93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
