"""Get authors

Revision ID: 8ac1795651a9
Revises: 22f2b1b119c9
Create Date: 2022-11-13 21:34:56.515288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac1795651a9'
down_revision = '22f2b1b119c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
