"""Move books

Revision ID: 95de9086e9d2
Revises: fc3875320759
Create Date: 2022-11-14 03:37:55.856268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95de9086e9d2'
down_revision = 'fc3875320759'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
