"""Final move

Revision ID: b7926e537d6b
Revises: eba9ad4a9224
Create Date: 2022-11-14 11:12:19.210845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7926e537d6b'
down_revision = 'eba9ad4a9224'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
