"""Fix delete 2

Revision ID: c373a0f766f4
Revises: f730a932e0d4
Create Date: 2022-11-20 20:05:39.727484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c373a0f766f4'
down_revision = 'f730a932e0d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
