"""Delete author

Revision ID: ce05225d3660
Revises: 891ed79e7711
Create Date: 2022-11-14 03:47:29.257560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce05225d3660'
down_revision = '891ed79e7711'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
