"""Fix delete 5

Revision ID: d88e56a271f8
Revises: 3877ad711dba
Create Date: 2022-11-20 20:16:23.227661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd88e56a271f8'
down_revision = '3877ad711dba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
