"""Get authors

Revision ID: de973418622b
Revises: b9c691ef511f
Create Date: 2022-11-13 21:17:55.223684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de973418622b'
down_revision = 'b9c691ef511f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
