"""Get authors

Revision ID: deb980edf89e
Revises: 8ac1795651a9
Create Date: 2022-11-13 21:36:21.794801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb980edf89e'
down_revision = '8ac1795651a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
