"""Delete vook

Revision ID: eba9ad4a9224
Revises: 440d11fffccd
Create Date: 2022-11-14 10:21:15.092654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eba9ad4a9224'
down_revision = '440d11fffccd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
