"""Fix delete

Revision ID: f730a932e0d4
Revises: 2254d19487dc
Create Date: 2022-11-20 20:04:05.292438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f730a932e0d4'
down_revision = '2254d19487dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
