"""Move books

Revision ID: fc3875320759
Revises: 70b5e4e26d04
Create Date: 2022-11-14 03:36:46.124642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc3875320759'
down_revision = '70b5e4e26d04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
