"""Fix delete 6

Revision ID: ff8b2f36d46f
Revises: d88e56a271f8
Create Date: 2022-11-20 20:18:47.258031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff8b2f36d46f'
down_revision = 'd88e56a271f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
